/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_live_network_RetrofitManager */

#ifndef _Included_com_live_network_RetrofitManager
#define _Included_com_live_network_RetrofitManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_live_network_RetrofitManager
 * Method:    getRemoteUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_live_network_RetrofitManager_getRemoteUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_live_network_RetrofitManager
 * Method:    getLocalDebugUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_live_network_RetrofitManager_getLocalDebugUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_live_network_RetrofitManager
 * Method:    getLocalUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_live_network_RetrofitManager_getLocalUrl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
